# GENERATED by npm run species:generate. DO NOT EDIT.
CATALOG = [
  [
    "Cantharellus cibarius",
    "species"
  ],
  [
    "Boletus",
    "genus"
  ],
  [
    "Morchella",
    "genus"
  ],
  [
    "Rubus fruticosus",
    "species"
  ],
  [
    "Sambucus nigra",
    "species"
  ],
  [
    "Urtica dioica",
    "species"
  ],
  [
    "Taraxacum officinale",
    "species"
  ],
  [
    "Corylus avellana",
    "species"
  ],
  [
    "Allium ursinum",
    "species"
  ],
  [
    "Laetiporus sulphureus",
    "species"
  ],
  [
    "Pleurotus ostreatus",
    "species"
  ],
  [
    "Lentinula edodes",
    "species"
  ],
  [
    "Rubus idaeus",
    "species"
  ],
  [
    "Vaccinium myrtillus",
    "species"
  ],
  [
    "Fragaria vesca",
    "species"
  ],
  [
    "Mentha arvensis",
    "species"
  ],
  [
    "Stellaria media",
    "species"
  ],
  [
    "Plantago major",
    "species"
  ],
  [
    "Juglans regia",
    "species"
  ],
  [
    "Castanea sativa",
    "species"
  ],
  [
    "Bellis perennis",
    "species"
  ],
  [
    "Viola odorata",
    "species"
  ],
  [
    "Amaranthus retroflexus",
    "species"
  ],
  [
    "Cynara cardunculus",
    "species"
  ],
  [
    "Asparagus acutifolius",
    "species"
  ],
  [
    "Craterellus cornucopioides",
    "species"
  ],
  [
    "Vaccinium vitis-idaea",
    "species"
  ],
  [
    "Peucedanum ostruthium",
    "species"
  ],
  [
    "Macrolepiota procera",
    "species"
  ],
  [
    "Rumex acetosa",
    "species"
  ],
  [
    "Calocybe gambosa",
    "species"
  ],
  [
    "Tuber melanosporum",
    "species"
  ]
]
CATALOG_NAMES = {name for name, _rank in CATALOG}
