/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsuseRouteImport } from './routes/termsuse'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as IndexRouteImport } from './routes/index'

const TermsuseRoute = TermsuseRouteImport.update({
  id: '/termsuse',
  path: '/termsuse',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/instructions': typeof InstructionsRoute
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/species': typeof SpeciesRoute
  '/support': typeof SupportRoute
  '/termsuse': typeof TermsuseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/instructions': typeof InstructionsRoute
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/species': typeof SpeciesRoute
  '/support': typeof SupportRoute
  '/termsuse': typeof TermsuseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/instructions': typeof InstructionsRoute
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/species': typeof SpeciesRoute
  '/support': typeof SupportRoute
  '/termsuse': typeof TermsuseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impressum'
    | '/instructions'
    | '/offline'
    | '/privacy-policy'
    | '/recipes'
    | '/settings'
    | '/species'
    | '/support'
    | '/termsuse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impressum'
    | '/instructions'
    | '/offline'
    | '/privacy-policy'
    | '/recipes'
    | '/settings'
    | '/species'
    | '/support'
    | '/termsuse'
  id:
    | '__root__'
    | '/'
    | '/impressum'
    | '/instructions'
    | '/offline'
    | '/privacy-policy'
    | '/recipes'
    | '/settings'
    | '/species'
    | '/support'
    | '/termsuse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumRoute: typeof ImpressumRoute
  InstructionsRoute: typeof InstructionsRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecipesRoute: typeof RecipesRoute
  SettingsRoute: typeof SettingsRoute
  SpeciesRoute: typeof SpeciesRoute
  SupportRoute: typeof SupportRoute
  TermsuseRoute: typeof TermsuseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termsuse': {
      id: '/termsuse'
      path: '/termsuse'
      fullPath: '/termsuse'
      preLoaderRoute: typeof TermsuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumRoute: ImpressumRoute,
  InstructionsRoute: InstructionsRoute,
  OfflineRoute: OfflineRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecipesRoute: RecipesRoute,
  SettingsRoute: SettingsRoute,
  SpeciesRoute: SpeciesRoute,
  SupportRoute: SupportRoute,
  TermsuseRoute: TermsuseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
