name: Track Unique Visitors

on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours at the start of the hour
#    - cron: "0 * * * *"  # Runs every hour at the start of the hour
#    - cron: "0,30 * * * *"  # Runs every 30 minutes

jobs:
  update-visitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_visitors.py script
        run: python fetch_visitors.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update visitor count"
          file_pattern: "visitors.json"

          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
